### ISSUE TITLE
Q: What is `gS` in VsVim sample mappings?

### ISSUE THREAD

**Issue by adam-c-anderson** [msomeone/PeasyMotion#13]
VsVim sample mappings include ones like this

`nnoremap <Space> gS:vsc Tools.InvokePeasyMotion<CR>`

As an intermediate Vimmer, I do not recognize the purpose of the `gS` portion of the mapped command. It's not documented, seems to behave only as `S` when executed in normal mode, and the mapping works the same without it AFAICT. What is `gS` for?

**Comment by msomeone** [comment]
It's actually for ViEmu compatibility, VsVim should do good without gS, but wonder if gS actually does something when used in VsVim.
So i've kept gS there, because  there is no need to duplicate mapping examples for VsVim and ViEmu separately. Sorry for confusing, maybe i should clarify this in mapping example comment line.

Here is part of ViEmu documentation for ref:
"An alternative if you want to use ViEmu's "emulated" selection, and you still need to go into VS-selection mode from time to time is to use the gS command when you need to do the conversion (this only lasts until the next ViEmu keypress)."

**Comment by adam-c-anderson** [comment]
Thanks for the clarification! I agree an explanation in the comment line would be helpful.

**Comment by msomeone** [comment]
Done! Thanks for reporting
