### ISSUE TITLE
Document Tab - cutting first letter

### ISSUE THREAD

**Issue by ghost** [msomeone/PeasyMotion#14]
I noticed that when I try use Document Tab future sometimes first couple of letters from name of file are missing. This is how tabs look like on beginning.
![image](https://user-images.githubusercontent.com/271887/82139051-7c02ed80-9825-11ea-877e-c96e7310d5bd.png)

When I execute Document Tab functionality it starts look like this
![image](https://user-images.githubusercontent.com/271887/82139071-a2288d80-9825-11ea-99c7-5437857c59be.png)

As you can see `TemperatureRepositry.cs` is replaced by `H|peratureRepository.cs` and for  `TemperatureService.cs` everything is working fine and I get `A|TemperatureService.cs`.

**Comment by msomeone** [comment]
The reason for described behaviour is that PeasyMotion intentionally tries to preserve document tab caption name.  Because if we change document tab caption character's count Visual Studio document tab refresh will kick in, and user may loose his gaze/focus on doctab he was willing to jump.

> TemperatureService.cs everything is working fine and I get A|TemperatureService.cs.
Actually, the filename is **Add**TemperatureService.cs, thats why it confuses you less, when "A" jump label is added.

My advice is to use monospaced fonts together with this feature, as it makes document tabs untouched, they will stay fixed and be easier to track/gaze under jump motions.

Sorry for confusing you.
I've updated README, and duplicating explanation here for your convenience:

> The only way to prevent UI 'jumping' when tabs caption are changed is to use monospaced font for Tools->Fonts And Colors -> show settings for Environment. This will help making tab captions keep stable.
When monospaced fonts are used in environment -> each character lower/upper of any kind occupies strictly the same space in title. This prevents any changes/adjustments to captions widths/doc title positions in combination with fact, that jump label replaces part of document name (to help with keeping document title the same width as it was).

**Comment by msomeone** [comment]
Let me know if anything else is wrong with doc tab. Thanks for your feedback!

**Comment by ghost** [comment]
Thanks for your explanations.
